#ifndef __DO_RMAHDR_
#define __DO_RMAHDR_

#ifdef __cplusplus
  extern "C" {
#endif

#define VCS_RTLIB_TLS_MODEL  __attribute__((tls_model("initial-exec")))

typedef unsigned long UP;
typedef unsigned U;
typedef unsigned char UB;
typedef unsigned short US;
typedef unsigned long long ULL;
typedef unsigned char scalar;
typedef struct vec32 vec32;
typedef unsigned char SVAL;
typedef unsigned char TYPEB;
typedef struct etype ETYPE;
typedef struct qird QIRD;
typedef unsigned char UST_e;
typedef unsigned uscope_t;
typedef U  NumLibs_t;
struct vec32 {
    U  I1;
    U  I2;
};
typedef unsigned long long InstNumType;
typedef long long InstNumSigned;
typedef InstNumType  InstNum;
typedef U  InstNum32;
typedef unsigned long RP;
typedef unsigned long RO;
typedef U  GateCount;
typedef U  NodeCount;
typedef unsigned short HsimEdge;
typedef unsigned char HsimExprChar;
typedef struct {
    U  I648;
    RP  I649;
} RmaReceiveClock1;
typedef NodeCount  FlatNodeNum;
typedef unsigned ProcessNum;
typedef unsigned long long TimeStamp64;
typedef unsigned long long TimeStamp;
typedef enum {
    PD_SING = 0,
    PD_RF = 1,
    PD_PLSE = 2,
    PD_PLSE_RF = 3,
    PD_NULL = 4
} PD_e;
typedef TimeStamp64  RmaTimeStamp64;
typedef TimeStamp  RmaTimeStamp;
typedef union {
    double I657;
    unsigned long long I658;
    unsigned  I659[2];
} rma_clock_struct;
typedef struct eblk EBLK;
typedef int (* E_fn)(void);
typedef struct eblk {
    E_fn  I666;
    struct iptmpl * I667;
    struct eblk * I669;
    unsigned I670;
    unsigned I671;
    struct eblk * I672;
    unsigned I256;
} eblk_struct;
typedef struct {
    RP  I666;
    RP  I667;
    RP  I669;
    unsigned I670;
    unsigned I671;
    RP  I672;
    unsigned I256;
} RmaEblk;
typedef struct {
    RP  I666;
    RP  I667;
    RP  I669;
    unsigned I670;
    unsigned I671;
    RP  I672;
    unsigned I256;
    unsigned val;
} RmaEblklq;
typedef struct _DEblkLaneT {
    struct _DEblkLaneT * I679;
    struct eblk * I681;
} DEblkLaneT;
typedef struct _DEblkPoolT {
    struct _DEblkLaneT * I682;
    struct _DEblkLaneT * I683;
    unsigned I684;
    unsigned I685;
} DEblkPoolT;
typedef union {
    double I657;
    unsigned long long I658;
    unsigned  I659[2];
} clock_struct;
typedef struct RmaRetain_t RmaRetain;
struct RmaRetain_t {
    RP  I716;
    RmaEblk  I665;
    ULL  I718;
    US  I719 :1;
    US  I720 :4;
    US  I234 :2;
    US  state :2;
    US  I722 :1;
    US  I723 :2;
    US  I724 :2;
    US  fHsim :1;
    US  I563 :1;
    scalar  newval;
    scalar  I727;
    RP  I728;
};
struct retain_t {
    struct retain_t * I716;
    EBLK  I665;
    ULL  I718;
    US  I719 :1;
    US  I720 :4;
    US  I234 :2;
    US  state :2;
    US  I722 :1;
    US  I723 :2;
    US  I724 :2;
    US  fHsim :1;
    US  I725 :1;
    scalar  newval;
    scalar  I727;
    void * I728;
};
typedef struct MPSched MPS;
typedef struct RmaMPSched RmaMps;
struct MPSched {
    MPS  * I707;
    scalar  I708;
    scalar  I709;
    scalar  I710;
    scalar  fHsim :1;
    scalar  I234 :6;
    U  I712;
    EBLK  I713;
    void * I714;
    UP   I715[1];
};
struct RmaMPSched {
    RP  I707;
    scalar  I708;
    scalar  I709;
    scalar  I710;
    scalar  fHsim :1;
    scalar  I234 :6;
    U  I712;
    RmaEblk  I713;
    RP  I714;
    RP   I715[1];
};
typedef struct RmaMPSchedPulse RmaMpsp;
struct RmaMPSchedPulse {
    RP  I707;
    scalar  I708;
    scalar  I709;
    scalar  I710;
    scalar  I234;
    U  I712;
    RmaEblk  I713;
    scalar  I724;
    scalar  I733;
    scalar  I734;
    scalar  I735;
    U  I736;
    U  I737;
    U  I738;
    U  state;
    U  I739;
    RP  I667;
    RP  I740;
    RP  I741;
    RP   I715[1];
};
typedef struct MPItem MPI;
struct MPItem {
    U  * I743;
    void * I744;
};
typedef struct {
    RmaEblk  I665;
    RP  I745;
    scalar  I746;
    scalar  I724;
    scalar  I747;
} RmaTransEventHdr;
typedef struct RmaMPSchedPulseNewCsdf RmaMpspNewCsdf;
struct RmaMPSchedPulseNewCsdf {
    RP  I707;
    scalar  I708;
    scalar  I709;
    scalar  I710;
    scalar  fHsim :1;
    scalar  I234 :6;
    U  I712;
    RmaEblk  I713;
    scalar  I724;
    scalar  I733;
    scalar  I734;
    scalar  I735;
    U  state :4;
    U  I749 :28;
    U  I737;
    U  I738;
    RP  I750;
    RP  I667;
    RP  I751;
    RP   I715[1];
};
typedef struct red_t {
    U  I752;
    U  I753;
    U  I626;
} RED;
typedef struct predd {
    PD_e  I234;
    RED   I754[0];
} PREDD;
union rhs_value {
    vec32  I755;
    scalar  I746;
    vec32  * I724;
    double I756;
    U  I757;
};
typedef struct nbs_t {
    struct nbs_t * I758;
    struct nbs_t * I760;
    void (* I761)(struct nbs_t * I728);
    U  I762 :1;
    U  I763 :1;
    U  I764 :1;
    U  I765 :1;
    U  I766 :1;
    U  I767 :1;
    U  I768 :26;
    U  I769;
    void * I770;
    union rhs_value I771;
    vec32  I657;
    union {
        struct nbs_t * I1253;
        struct nbs_t * last;
    } I773;
} NBS;
typedef struct {
    RP  I774;
    RP  I740;
    RP  I667;
    RP  I741;
    RmaEblk  I665;
    RmaEblk  I775;
    RP  I776;
    scalar  I746;
    scalar  I724;
    char state;
    uscope_t  I777;
    U  I778;
    RP  I779;
    scalar  I733;
    scalar  I734;
    scalar  I735;
    U  I737;
    U  I738;
    RP  I714;
} RmaPulse;
typedef enum {
    QIRDModuleC = 1,
    QIRDSVPackageC = 2,
    QIRDSpiceModuleC = 3
} QIRDModuleType;
typedef struct {
    U  I783 :1;
    U  I784 :1;
    U  I785 :1;
    U  I786 :1;
    U  I787 :1;
    U  I788 :1;
    U  I789 :1;
    U  I790 :1;
    U  I791 :1;
    U  I792 :1;
    U  I793 :1;
    U  I794 :1;
    U  I795 :1;
    U  I796 :1;
    U  I797 :1;
    U  I798 :1;
    U  I799 :1;
    U  I800 :1;
    U  I801 :1;
    QIRDModuleType  I802 :2;
    U  I803 :1;
    U  I804 :1;
    U  I805 :1;
    U  I806 :1;
    U  I807 :1;
    U  I808 :1;
    U  I809 :1;
    U  I810 :1;
    U  I811 :1;
    U  I812 :1;
    U  I813 :1;
    U  I814 :1;
    U  I815 :1;
    U  I816 :1;
    U  I817 :1;
    U  I818 :1;
    U  I819 :1;
    U  I820 :1;
    U  I821 :1;
    U  I822 :1;
    U  I823 :1;
    U  I824 :1;
    U  I825 :1;
    U  I826 :1;
    U  I827 :1;
    U  I828 :1;
    U  I829 :1;
    U  I830 :1;
    U  I831 :1;
    U  I832 :1;
    U  I833 :1;
    U  I834 :1;
    U  I835 :1;
    U  I836 :10;
} BitFlags;
typedef struct qird_dbg_flags_s {
    U  I837 :29;
    U  I838 :1;
    U  I839 :1;
    U  I840 :1;
} qird_dbg_flags_t;
typedef struct nlpInfoT {
    U  * I841;
    U  * I842;
    U  * I843;
    UP  * I844;
    UP  * I845;
    UP  * I846;
    UP  * I847;
    char * I848;
    UP  * I849;
    UP  * I850;
    U  * I851;
    UP  * I852;
    UP  * I853;
    UP  * I854;
    UP  * I855;
    UP  * I856;
    UP  * I857;
    UP  * I858;
    UP  * I859;
    UP  * I860;
    UP  * I861;
    UP  * I862;
    UP  * I863;
    UP  * I864;
    UP  * I865;
    char * I866;
    char * I867;
    U  * I868;
    UP  * I869;
    UP  * I870;
    UP  * I871;
    UP  * I872;
    UP  * I873;
    UP  * I874;
    UP  * I875;
    UP  * I876;
    UP  * I877;
    UP  * I878;
    UP  * I879;
    UP  * I880;
    UP  * I881;
    UP  * I882;
    UP  * I883;
    UP  * I884;
    U  I885;
    U  I886;
    U  I887;
    U  I888;
    U  I889;
    U  I890;
    U  I891;
    U  I892;
    U  I893;
    U  I894;
    U  I895;
    U  I896;
    U  I897;
    U  I898;
    U  I899;
    U  I900;
    U  I901;
    U  I902;
} nlpInfoT;
typedef struct txpInfoT {
    U  I903;
    U  I904;
    void * I905;
    void * I906;
    int (* I907)(void);
    int (* I908)(void);
    void * I909;
    void * I910;
    void * I911;
} txpInfoT;
typedef struct fsimInfoT {
    U  I912;
    U  I913;
    U  * I914;
    U  * I915;
    UP  * I916;
    UP  * I917;
    U  * I918;
    U  * I919;
    U  * I920;
} fsimInfoT;
typedef struct fgpInfoT {
    U  I921;
    U  I922;
    U  * I923;
    U  * I924;
    char * I925;
} fgpInfoT;
typedef struct peDummyModInfoT {
    char * I926;
    char * I927;
    char * I928;
} peDummyModInfoT;
typedef struct peModInfoT {
    char * I62;
    char * I929;
    char * I930;
    U  I931;
    peDummyModInfoT  * I932;
} peModInfoT;
typedef struct simProfInfoT {
    U  I933;
    U  I934;
    U  I935;
    U  * I936;
    U  * I937;
    U  * I938;
    U  * I939;
} simProfInfoT;
typedef struct hybridSimInfoT {
    U  I940;
    U  I629;
    U  I941;
    U  I942;
    U  I943;
    void * I944;
    U  * I945;
    struct hybridSimReferrerData * I946;
    struct hybridSimReferrerData * I948;
} hybridSimInfoT;
typedef struct classInfoT {
    void * I949;
    void * I950;
    void * I951;
    U  I952;
    U  I953;
    U  I954;
    U  I955;
    UP  I956;
    UP  I957;
    void * I958;
} classInfoT;
struct qird {
    US  I58;
    US  I59;
    U  I60;
    U  I61;
    char * I62;
    char * I63;
    U  * I64;
    char * I65;
    char * I66;
    U  I67;
    U  I68;
    struct vcd_rt * I69;
    U  I71;
    struct _vcdOffset_rt * I72;
    U  I74;
    U  I75;
    ETYPE  * I76;
    U  * I77;
    classInfoT  * I78;
    int I79;
    U  I80;
    U  * I81;
    U  * I82;
    UP  I83;
    UP  * I84;
    BitFlags  I85;
    U  I86;
    U  I87;
    U  I88;
    U  I89;
    U  * I90;
    U  I91;
    U  I92;
    U  * I93;
    U  I94;
    U  I95;
    U  I96;
    U  I97;
    U  I98;
    U  I99;
    U  I100;
    U  I101;
    U  * I102;
    U  * I103;
    U  * I104;
    U  I105;
    U  I106;
    U  * I107;
    U  I108;
    U  I109;
    U  I110;
    U  I111;
    U  * I112;
    U  I113;
    U  * I114;
    U  I115;
    U  I116;
    U  I117;
    U  I118;
    U  I119;
    U  I120;
    U  * I121;
    char * I122;
    U  I123;
    U  I124;
    U  I125;
    U  I126;
    U  * I127;
    U  I128;
    U  I129;
    U  I130;
    U  I131;
    UP  * I132;
    U  I133;
    U  I134;
    U  I135;
    U  I136;
    U  I137;
    U  I138;
    U  * I139;
    U  I140;
    U  I141;
    U  * I142;
    U  * I143;
    U  * I144;
    U  * I145;
    U  * I146;
    U  I147;
    U  I148;
    struct taskInfo * I149;
    U  I151;
    U  I152;
    U  I153;
    U  I154;
    int * I155;
    U  * I156;
    UP  * I157;
    U  * I158;
    U  I159;
    U  I160;
    int * I161;
    U  I162;
    U  I163;
    U  I164;
    U  I165;
    U  I166;
    U  I167;
    struct qrefer * I168;
    U  * I170;
    unsigned * I171;
    void * I172;
    U  I173;
    struct classStaticReferData * I174;
    U  I176;
    U  * I177;
    U  I178;
    U  * I179;
    U  I180;
    struct wakeupInfoStruct * I181;
    U  I183;
    U  I184;
    U  I185;
    U  * I186;
    U  I187;
    U  * I188;
    U  * I189;
    U  I190;
    U  I191;
    U  I192;
    U  I193;
    U  * I194;
    U  I195;
    U  I196;
    U  * I197;
    U  I198;
    U  I199;
    U  * I200;
    U  * I201;
    U  * I202;
    U  I203;
    U  I204;
    U  I205;
    U  I206;
    U  I207;
    U  I208;
    struct qdefrefee * I209;
    struct qrefee * I211;
    U  * I213;
    U  * I214;
    int (* I215)(void);
    char * I216;
    U  I217;
    U  I218;
    void * I219;
    void * I220;
    NumLibs_t  I221;
    char * I222;
    U  * I223;
    U  I224;
    U  I225;
    U  I226;
    U  I227;
    U  I228;
    U  * I229;
    U  * I230;
    int I231;
    struct clock_load * I232;
    int I247;
    struct clock_data * I248;
    int I264;
    struct clock_hiconn * I265;
    U  I269;
    U  I270;
    U  I271;
    U  I272;
    U  * I273;
    U  I274;
    U  I275;
    U  * I276;
    U  I277;
    void * I278;
    U  I279;
    U  I280;
    UP  * I281;
    void * I282;
    U  I283;
    UP  * I284;
    U  * I285;
    int (* I286)(void);
    U  * I287;
    UP  * I288;
    U  * I289;
    U  I290 :1;
    U  I291 :31;
    U  I292;
    U  I293;
    UP  * I294;
    U  * I295;
    U  I296 :1;
    U  I297 :1;
    U  I298 :1;
    U  I299 :1;
    U  I300 :28;
    U  I301;
    U  I302;
    U  I303;
    U  I304 :31;
    U  I305 :1;
    UP  * I306;
    UP  * I307;
    fsimInfoT  * I308;
    nlpInfoT  * I309;
    U  I310;
    U  I311;
    UP  * I312;
    UP  * I313;
    UP  * I314;
    UP  * I315;
    struct daidirInfo * I316;
    struct vcs_tftable * I318;
    U  I320;
    UP  * I321;
    UP  * I322;
    U  I323;
    U  I324;
    U  I325;
    UP  * I326;
    U  * I327;
    UP  * I328;
    UP  * I329;
    struct qird_hil_data * I330;
    U  I332;
    U  * I333;
    UP  (* I334)(void);
    UP  (* I335)(void);
    UP  (* I336)(void);
    UP  (* I337)(void);
    UP  (* I338)(void);
    int * I339;
    int (* I340)(void);
    char * I341;
    UP  * I342;
    UP  * I343;
    UP  (* I344)(void);
    int (* I345)(void);
    int * I346;
    int (* I347)(void);
    int (* I348)(void);
    int * I349;
    char * I350;
    U  * I351;
    U  * I352;
    U  * I353;
    U  * I354;
    void * I355;
    int (* I356)(void);
    U  I357;
    UP  * I358;
    UP  * I359;
    U  I360;
    void * I361;
    U  I362;
    U  I363;
    U  I364;
    U  I365;
    U  I366;
    U  I367;
    char * I368;
    UP  * I369;
    U  * I370;
    UP  * I371;
    U  * I372;
    U  * I373;
    U  I374 :15;
    U  I375 :14;
    U  I376 :1;
    U  I377 :1;
    U  I378 :1;
    U  I379 :3;
    U  I380 :1;
    U  I381 :1;
    U  I382 :17;
    U  I383 :3;
    U  I384 :5;
    U  I385 :1;
    U  I386 :1;
    U  I387;
    qird_dbg_flags_t  I388;
    struct scope * I389;
    U  I391;
    U  I392;
    U  I393;
    U  * I394;
    U  * I395;
    U  * I396;
    U  I397;
    U  I398;
    U  I399;
    U  I400;
    struct pcbt * I401;
    UP  * I410;
    U  I411;
    U  I412;
    U  I413;
    U  I414;
    void * I415;
    void * I416;
    void * I417;
    int I418;
    U  * I419;
    U  I420;
    U  I421;
    UP  * I422;
    U  I423;
    U  I424;
    U  I425;
    U  I426;
    U  I427;
    void * I428;
    UP  * I429;
    U  I430;
    U  I431;
    void * I432;
    U  I433;
    txpInfoT  * I434;
    U  I435;
    U  I436;
    U  I437;
    U  I438;
    U  I439;
    U  I440;
    char * I441;
    U  I442;
    U  * I443;
    U  I444;
    U  * I445;
    U  I446;
    U  I447;
    U  I448;
    U  I449;
    U  I450;
    U  I451;
    U  * I452;
    U  I453;
    U  I454;
    U  * I455;
    U  I456;
    U  I457;
    U  I458;
    U  * I459;
    char * I460;
    U  I461;
    U  I462;
    U  I463;
    simProfInfoT  * I464;
    U  I465;
    U  I466;
    UP  * I467;
    U  I468;
    U  I469;
    U  I470;
    struct cosim_info * I471;
    U  I473;
    U  * I474;
    hybridSimInfoT  * I475;
    U  * I476;
    U  I477;
    U  I478;
    U  * I479;
    U  I480;
    U  I481;
    U  * I482;
    U  I483;
    U  * I484;
    U  I485;
    U  * I486;
    U  I487;
    U  I488;
    U  * I489;
    U  I490;
    U  * I491;
    U  I492;
    U  I493;
    U  * I494;
    struct mhdl_outInfo * I495;
    UP  * I497;
    U  I498;
    UP  * I499;
    U  I500;
    void * I501;
    U  * I502;
    void * I503;
    char * I504;
    U  I505;
    U  * I506;
    char * I507;
    U  I508;
    struct regInitInfo * I509;
    UP  * I511;
    U  * I512;
    char * I513;
    U  I514;
    U  I515;
    U  I516;
    U  I517;
    U  I518;
    U  I519;
    U  I520;
    U  I521;
    UP  * I522;
    U  I523;
    U  I524;
    U  I525;
    UP  * I526;
    U  I527;
    UP  * I528;
    U  I529;
    UP  * I530;
    U  I531;
    U  I532;
    U  I533;
    U  * I534;
    U  I535;
    U  I536;
    U  I537;
    U  * I538;
    U  * I539;
    UP  * I540;
    UP  * I541;
    void * I542;
    UP  I543;
    void * I544;
    void * I545;
    void * I546;
    void * I547;
    void * I548;
    UP  I549;
    U  * I550;
    U  * I551;
    void * I552;
    U  I553 :1;
    U  I554 :31;
    U  I555;
    U  I556;
    U  I557;
    int I558;
    U  I559 :1;
    U  I560 :1;
    U  I561 :1;
    U  I562 :1;
    U  I563 :28;
    void * I564;
    void * I565;
    void * I566;
    void * I567;
    void * I568;
    void * I569;
    void * I570;
    UP  * I571;
    U  * I572;
    U  I573;
    char * I574;
    U  * I575;
    U  * I576;
    U  * I577;
    char * I578;
    int * I579;
    int * I580;
    UP  * I581;
    struct etype * I582;
    U  I583;
    U  I584;
    U  * I585;
    struct etype * I586;
    U  I587;
    U  I588;
    U  I589;
    U  * I590;
    void * I591;
    U  I592;
    U  I593;
    void * I594;
    fgpInfoT  * I595;
    U  I596;
    peModInfoT  * I597;
    U  I598;
    struct covreg_rt * I599;
    U  I601;
    U  I602;
    U  * I603;
    U  * I604;
    U  I605;
    U  I606;
};
typedef struct pcbt {
    U  * I403;
    UP  I78;
    U  I404;
    U  I405;
    U  I406;
    U  I407;
    U  I408;
    U  I409;
} PCBT;
typedef struct {
    int * I959;
    int * I960;
    int I961;
    union {
        long long enumDesc;
        long long classId;
    } I962;
} TypeData;
struct etype {
    U  I4 :8;
    U  I5;
    U  I6;
    U  I7 :1;
    U  I8 :1;
    U  I9 :1;
    U  I10 :1;
    U  I11 :1;
    U  I12 :1;
    U  I13 :1;
    U  I14 :1;
    U  I15 :1;
    U  I16 :4;
    U  I17 :1;
    U  I18 :1;
    U  I19 :1;
    U  I20 :1;
    U  I21 :1;
    U  I22 :1;
    U  I23 :1;
    U  I24 :1;
    U  I25 :2;
    U  I26 :1;
    U  I27 :2;
    U  I28 :1;
    U  I29 :1;
    U  I30 :1;
    U  I31 :1;
    U  I32 :1;
    U  I33 :1;
    TypeData  * I34;
    U  I35;
    U  I36;
    U  I37 :1;
    U  I38 :1;
    U  I39 :1;
    U  I40 :1;
    U  I41 :2;
    U  I42 :2;
    U  I43 :1;
    U  I44 :1;
    U  I45 :1;
    U  I46 :1;
    U  I47 :1;
    U  I48 :1;
    U  I49 :1;
    U  I50 :1;
    U  I51 :1;
    U  I52 :1;
    U  I53 :1;
    U  I54 :1;
    U  I55 :1;
    U  I56 :11;
};
struct iptmpl {
    QIRD  * I673;
    void * I674;
    UP  I675;
    UP  I676;
    UP  I677;
    struct iptmpl * I678[2];
};
typedef unsigned long long FileOffset;
typedef struct _HsCgPeriod {
    U  I1022;
    U  I1023;
} HsCgPeriod;
typedef struct {
    U   I1024[2];
    U  I1025 :1;
    U  I1026 :1;
    U  I1027 :8;
    U  I1028 :8;
    U  I1029 :8;
    U  I1030 :4;
    U  I1031 :1;
    U  I1032 :1;
    unsigned long long I1033;
    unsigned long long I1034;
    unsigned long long I1035;
    unsigned long long I1036;
    unsigned long long I1023;
    U  I1022;
    U  I1037;
    U  I1038;
    U  I1039;
    U  I1040;
    U  I1041;
    HsCgPeriod  * I1042[10];
} HsimSignalMonitor;
typedef struct {
    InstNum  I1043;
    FlatNodeNum  I1044;
    U  I977;
    scalar  I1045;
    UB  I1046;
    UB  I1047;
    UB  I1048;
    UB  I1049;
    UB  I1050;
    UB  I1051;
    ULL  I1052;
    U  I1053;
    U  I1054;
    U  I1055;
    U  I1056;
    U  I1057;
    U  I1058;
    U  I1059;
    U  I1060;
    HsimSignalMonitor  * I1061;
    RP  I1062;
    RmaTimeStamp64  I1063;
    U  I1064;
    RmaTimeStamp64  I1065;
    U  I1066;
    UB  I1067 :1;
    UB  I1068 :1;
    UB  I1069 :1;
    ULL  I1070;
    ULL  I1071;
    ULL  I1072;
    ULL  I1073;
    ULL  I1022;
    U  I1074;
    U  I1075;
    ULL  I1076;
    ULL  I1077;
    ULL  I1078;
    ULL  I1079;
    RP  I1080;
} HsimNodeRecord;
typedef struct {
    RP  I1088;
    RP  pcode;
} RmaIbfPcode;
typedef struct {
    RP  I1088;
    RP  I667;
} RmaIbfIp;
typedef struct {
    RP  I1088;
    RP  I667;
    U  I256;
} RmaIbfIp_RTS;
typedef struct {
    U  I761;
    InstNum32  I632;
} RmaIbfIpById;
typedef struct {
    U  I670;
    U  val;
} RmaDynamicEblklq;
typedef struct {
    U  I670;
    U  I671;
} RmaFgpDynamicEblklq;
typedef struct {
    U  val;
} RmaDynamicEblk;
typedef struct {
    scalar  I1089;
    UB  I1090;
    US  I1091;
} JaguarClockGlitch;
typedef struct {
    U  I653 :28;
    U  I1092 :1;
    U  I1093 :1;
    U  I1094 :1;
    U  I1095 :1;
    U  I1096;
    RP  I1097;
    RP  I1098;
    RP  I1099;
    U   I1100[1];
} RmaDbsedRtlLoads;
typedef struct {
    RP  I1101;
    RP  pfn;
    RP  pcode;
} RmaSeqPrimOutputEblkData;
typedef RP  RCICODE;
typedef struct {
    RmaEblk  I665;
} RmaEvTriggeredOrSyncLoadCg;
typedef struct {
    RO  I966;
    RP  pcode;
} SchedGateFanout;
typedef struct {
    RO  I966;
    RP  pcode;
    U   I1000[4];
} SchedSelectGateFanout;
typedef struct {
    RP  pcode;
    RmaEblklq  I665;
} SchedGateEblk;
typedef struct {
    RP  pcode;
    RmaEblklq  I665;
    UB  * I1102;
} SchedSelectGateEblk;
typedef struct {
    RP  pcode;
    RP  I666;
    RP  I667;
    UB  * I1102;
} SchedSelectGateCall;
typedef struct {
    RmaEblk  I665;
    RP  I1103;
} RmaAnySchedSampleSCg;
typedef struct {
    RmaEblk  I665;
    RP  I1102;
    RP  I1103;
    vec32  I1104;
} RmaAnySchedVCg;
typedef struct {
    RmaEblk  I665;
    RP  I1102;
    RP  I1103;
    vec32   I723[1];
} RmaAnySchedWCg;
typedef struct {
    RmaEblk  I665;
    RP  I1102;
    RP  I1103;
    scalar   I1105[1];
} RmaAnySchedECg;
typedef struct {
    U  I1106;
    U  I653;
    U  I977;
    U  I1107;
    RmaIbfIp  * I1108;
    EBLK  I665;
    void * val;
} RmaThreadSchedCompiledLoads;
typedef struct {
    U  I653;
    U  I661;
    RmaThreadSchedCompiledLoads  * I1109;
} RmaSchedCompileLoadsCg;
typedef RmaThreadSchedCompiledLoads  ** RmaThreadSchedCompiledLoadsArr;
typedef struct {
    U  I1110;
    U  I1111;
    RmaIbfIp  * I1112;
    RmaThreadSchedCompiledLoadsArr  I1113;
} RmaJaguarIbnSchedCg;
typedef struct {
    RP  I1114;
} RmaRootCbkCg;
typedef struct {
    RP  I1115;
} RmaRootForceCbkCg;
typedef struct {
    RmaEblk  I665;
    RP  I1116;
} RmaForceCbkJmpCg;
typedef struct {
    U  I59;
    U  I661 :31;
    U  I1117 :1;
    vec32  I755;
    U  I1118;
    RP  I1119;
    RP  I1120;
} RmaForceSelectorV;
typedef struct {
    U  I59;
    RmaIbfPcode  I1127;
} RmaNetTypeDriverGate;
typedef struct {
    U  I59;
    U  I610;
    RmaIbfPcode   I1127[1];
} RmaNetTypeScatterGate;
typedef struct {
    U  I59;
    RmaIbfPcode  I1127;
} RmaNetTypeGatherGate;
typedef struct {
    RmaIbfPcode  I1128;
    U  I1129 :3;
    U  I1130 :1;
    U  I1131 :1;
    U  I1132 :16;
} RmaNbaGateOfn;
typedef struct {
    U  I59;
    NBS  I1133;
    RmaIbfPcode  I1128;
} RmaNbaGate1;
typedef struct {
    RP  ptable;
    RP  pfn;
    RP  pcode;
} Rma1InputGateFaninCgS;
typedef struct RmaSeqPrimOutputS_ RmaSeqPrimOutputOnClkS;
struct RmaSeqPrimOutputS_ {
    RP  pfn;
    U  state;
    U  I1136;
    RP  I1137;
    scalar  val;
    scalar  I1138;
    union {
        U  I648;
        U  I630;
    } I641;
    RP   I1139[1];
};
typedef struct RmaSimonFlopOutputV_ RmaSimonFlopOutputV;
typedef struct RmaSimonLatchOutputV_ RmaSimonLatchOutputV;
struct RmaSimonFlopOutputV_ {
    RP  pfn;
    RP  I1141;
    RP  I1142;
};
typedef struct RmaSimonResetFlopOutputV_ RmaSimonResetFlopOutputV;
struct RmaSimonResetFlopOutputV_ {
    RP  pfn;
    RP  I1141;
    RP  I1142;
    RP  I1146;
    scalar  I1147;
};
struct RmaSimonLatchOutputV_ {
    RP  pfn;
    RP  I1141;
    RP  I1142;
    scalar  I1144;
};
typedef struct {
    U  I59;
    U  iinput;
    UB  I1149;
    RP  I1150;
} RmaCondOptLoad;
typedef struct {
    U  I59;
    U  iinput;
    UB  I1149;
    RP  I1150;
} RmaMacroStateUpdate;
typedef struct {
    U  I59;
    U  state;
    U  I1151;
    UB  I1149;
    U  * I1152;
} RmaMacroState;
typedef struct {
    U  iinput;
    RP  I1153;
} RmaMultiInputLogicGateCg;
typedef struct {
    U  iinput;
    RP  ptable;
    RP  I1153;
} RmaSeqPrimEdgeInputCg;
typedef struct {
    RP  I1153;
} RmaSimonCellEdgeInputCg;
typedef struct {
    RmaEblk  I665;
    RP  pcode;
} RmaSched0GateCg;
typedef struct {
    RmaEblk  I665;
    RP  pcode;
    RP  pfn;
    scalar  I647;
    scalar  I1154;
} RmaUdpDeltaGateCg;
typedef struct {
    RmaEblk  I665;
    RP  pcode;
    RP  pfn;
    scalar  I1155;
} RmaSchedDeltaGateCg;
typedef struct {
    RP  pcode;
    RP  pfn;
    RmaDynamicEblk  I665;
    scalar  I1155;
    scalar  I1156;
    scalar  I1157;
    scalar  I563;
} RmaDynamicSchedDeltaGateCg;
typedef struct {
    UB  I1158;
    RP  I1159;
    RP  I1160;
} RmaPropNodeSeqLhsSCg;
typedef struct {
    RmaEblk  I665;
    RP  pcode;
    U  I977;
    U   I654[1];
} RmaBitEdgeEblk;
typedef struct {
    U  I59;
    U  I1161;
    RP  I754;
    RmaEblk  I665;
    RmaIbfPcode  I1128;
} RmaGateDelay;
typedef struct {
    U  I59;
    RP  I754;
    RmaEblk  I665;
    RmaIbfPcode  I1128;
} RmaGateBehavioralDelay;
typedef struct {
    U  I59;
    union {
        RP  I1425;
        RP  I1732;
        RP  I1749;
    } I728;
    RmaIbfPcode  I1128;
} RmaMPDelay;
typedef struct {
    U  I59;
    RmaPulse  I1162;
    RmaIbfPcode  I1128;
} RmaMPPulseHybridDelay;
typedef struct {
    U  I59;
    RmaIbfPcode  I1128;
    RmaMps  I1163;
} RmaMPHybridDelay;
typedef struct {
    U  I59;
    U  I1164;
    RmaIbfPcode  I1128;
    RmaEblk  I713;
} RmaMPHybridDelayPacked;
typedef struct {
    U  I59;
    RmaIbfPcode  I1128;
    RmaMpspNewCsdf  I1165;
} RmaMPPulseDelay;
typedef struct {
    U  I59;
    RmaMpsp  I1165;
    RmaIbfPcode  I1128;
} RmaMPPulseOptHybridDelay;
typedef struct _RmaBehavioralTransportDelay {
    U  I59;
    RP  I626;
    RmaTransEventHdr  I983;
    RP  I751;
    RmaIbfPcode  I1128;
} RmaBehavioralTransportDelayS;
typedef struct {
    U  I59;
    RP  I626;
    RmaTransEventHdr  I983;
    RP  I751;
    RmaIbfPcode  I1128;
} RmaNtcTransDelay;
typedef struct {
    U  I59;
    RP  I626;
    RmaEblk  I665;
    RmaIbfPcode  I1128;
} RmaNtcTransMpwOptDelay;
typedef struct {
    U  I59;
    RmaEblk  I665;
    RmaIbfPcode  I1128;
} RmaNtcTransZeroDelay;
typedef struct {
    U  I59;
    RP  I1166;
    RP  I1167;
    RmaTransEventHdr  I983;
    RP  I751;
    RmaIbfPcode  I1128;
} RmaNtcTransDelayRF;
typedef struct {
    U  I59;
    RP  I1166;
    RP  I1167;
    RmaEblk  I665;
    RmaIbfPcode  I1128;
} RmaNtcTransMpwOptDelayRF;
typedef struct {
    U  I59;
    RP  I1168;
    RmaTransEventHdr  I983;
    RP  I751;
    RmaIbfPcode  I1128;
} RmaICTransDelay;
typedef struct {
    U  I59;
    RP  I1168;
    RmaEblk  I665;
    RmaIbfPcode  I1128;
} RmaICTransMpwOptDelay;
typedef struct {
    U  I59;
    RmaEblk  I665;
    RmaIbfPcode  I1128;
} RmaICTransZeroDelay;
typedef struct {
    U  I59;
    RP  I754;
    RmaEblk  I665;
    RmaIbfPcode  I1128;
} RmaICSimpleDelay;
typedef struct {
    U  I59;
    union {
        RP  psimple;
        RP  I1732;
        RP  I1749;
    } I728;
    RmaIbfPcode  I1128;
} RmaICDelay;
typedef struct {
    U  I59;
    RP  I754;
    RmaEblk  I665;
    RmaIbfPcode  I1128;
} RmaPortDelay;
typedef struct {
    U  I1132;
    RP  I1169;
} RmaRtlXEdgesLoad;
typedef struct {
    U  I59;
    RmaRtlXEdgesLoad   I1169[(5)];
    void * I1170;
} RmaRtlXEdgesHdr;
typedef struct {
    U  I59;
    US  I1171;
    US  I1172 :1;
    US  I836 :15;
    RP  I1173;
    RP  I1174;
    RP  I1175;
} RmaRtlEdgeBlockHdr;
typedef struct {
    RP  I1176;
    RP  I1177;
} RemoteDbsedLoad;
typedef struct {
    RmaEblk  I665;
    RP  I1178;
    RP  I1179;
    US  I1180;
    UB  I1181;
    UB  I1182 :2;
    UB  I1183 :2;
    UB  I1184 :1;
    UB  I836 :3;
    U  I629;
    RP  I1185;
    RP   I758[(5)];
    RP   I760[(5)];
    US  I1186;
    US  I1187;
    RP  I1188;
    RemoteDbsedLoad   I1189[1];
} RmaRtlEdgeBlock;
typedef struct TableAssign_ {
    struct TableAssign_ * I969;
    struct TableAssign_ * I745;
    U  I59;
    U  I1191 :1;
    U  I1192 :1;
    U  I1193 :2;
    U  I1194 :1;
    U  I648 :8;
    U  I1195 :1;
    U  I1196 :1;
    U  I1197 :1;
    U  I1198 :1;
    U  I1199 :1;
    U  I1200 :1;
    U  I1201 :1;
    U  I1202 :1;
    U  I1203 :1;
    U  I1204 :1;
    U  I836 :9;
    RP  ptable;
    RP  I1153;
} TableAssign;
typedef struct TableAssignLayoutOnClk_ {
    struct TableAssignLayoutOnClk_ * I969;
    struct TableAssignLayoutOnClk_ * I745;
    U  I59;
    U  I1191 :1;
    U  I1192 :1;
    U  I1193 :2;
    U  I1194 :1;
    U  I648 :8;
    U  I1195 :1;
    U  I1196 :1;
    U  I1197 :1;
    U  I1198 :1;
    U  I1199 :1;
    U  I1200 :1;
    U  I1201 :1;
    U  I1202 :1;
    U  I1203 :1;
    U  I1204 :1;
    U  I836 :9;
    RP  ptable;
    RmaSeqPrimOutputOnClkS  I1206;
    RmaEblk  I665;
} TableAssignLayoutOnClk;
typedef struct {
    U  state;
    U  I1207;
} RmaSeqPrimOutputOnClkOpt;
typedef struct TableAssignLayoutOnClkOpt_ {
    struct TableAssignLayoutOnClkOpt_ * I969;
    struct TableAssignLayoutOnClkOpt_ * I745;
    U  I1209;
    U  I1191 :1;
    U  I1192 :1;
    U  I1193 :2;
    U  I1194 :1;
    U  I648 :8;
    U  I1195 :1;
    U  I1196 :1;
    U  I1197 :1;
    U  I1198 :1;
    U  I1199 :1;
    U  I1200 :1;
    U  I1201 :1;
    U  I1202 :1;
    U  I1203 :1;
    U  I1204 :1;
    U  I836 :9;
    union {
        U  I1211;
        RP  ptable;
    } table;
    RmaSeqPrimOutputOnClkOpt  I1206;
    RmaSeqPrimOutputEblkData  I1212;
} TableAssignLayoutOnClkOpt;
typedef struct {
    U  I59;
    RP  I745;
    RP  I1213;
} RmaTableAssignList;
typedef struct {
    U  I59;
    RP  I745;
    RP  I1213;
    RP  I1214;
    RP  I1137;
    RP  I1215;
    US  I648;
    UB  I1045;
    UB  I1216;
    UB  I1217;
    UB  I719;
    RP   I1218[0];
} RmaThreadTableAssignList;
typedef struct {
    RP  I1214;
    RP  I1137;
    RP  I1215;
    U  I1219 :1;
    U  I1099 :8;
    U  I1220 :8;
    U  I1221 :1;
    U  I836 :14;
    US  I648;
    UB  I1045;
    UB  I1216;
    UB  I1217;
    UB  I719;
} RmaThreadTableHeader;
typedef struct {
    RP  I1176;
} RmaWakeupListCg;
typedef struct {
    RP  I1176;
} RmaWakeupArrayCg;
typedef struct {
    RP  I1176;
    RP  I1222;
} RmaPreCheckWakeupListCg;
typedef struct {
    RP  I1176;
    RP  I1222;
} RmaPreCheckWakeupArrayCg;
typedef struct {
    U  I1223;
    U  I648;
    RmaTimeStamp   I1224[1];
} RmaTsArray;
typedef struct {
    U  iinput;
    RP  I1225;
} RmaConditionsMdb;
typedef struct {
    RP  I1226;
    RP  I1227;
    U  I1228;
} RmaTcListHeader;
typedef struct {
    RP  I969;
    RP  I1229;
    RP  I1230;
    RP  I660;
    U  I1231;
    scalar  I1132;
    scalar  I1232;
    US  I1233 :1;
    US  I1234 :1;
    US  I1235 :1;
    US  I1236 :1;
    US  I1237 :1;
    US  I1238 :1;
    US  I1239 :1;
    US  I1240 :5;
} RmaTcCoreSimple;
typedef struct {
    RP  I969;
    RP  I1229;
    RP  I1230;
    RP  I660;
    U  I1231;
    scalar  I1132;
    scalar  I1232;
    US  I1233 :1;
    US  I1234 :1;
    US  I1235 :1;
    US  I1236 :1;
    US  I1237 :1;
    US  I1238 :1;
    US  I1239 :1;
    US  I1240 :5;
    RP  I1241;
} RmaTcCoreConditional;
typedef struct {
    RP  I969;
    RP  I1229;
    RP  I1230;
    RP  I660;
    U  I1231;
    scalar  I1132;
    scalar  I1232;
    US  I1233 :1;
    US  I1234 :1;
    US  I1235 :1;
    US  I1236 :1;
    US  I1237 :1;
    US  I1238 :1;
    US  I1239 :1;
    US  I1240 :5;
    RP  I1241;
    RP  I1242;
} RmaTcCoreConditionalOpt;
typedef struct {
    RP  I969;
    RP  I1229;
    RP  I1230;
    RP  I660;
    U  I1231;
    scalar  I1132;
    scalar  I1232;
    US  I1233 :1;
    US  I1234 :1;
    US  I1235 :1;
    US  I1236 :1;
    US  I1237 :1;
    US  I1238 :1;
    US  I1239 :1;
    US  I1240 :5;
    RP  I1242;
    RP  I1243;
    U  I1244;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtc;
typedef struct {
    RP  I1230;
    RP  I660;
    U  I1231;
    scalar  I1132;
    scalar  I1232;
    US  I1233 :1;
    US  I1234 :1;
    US  I1235 :1;
    US  I1236 :1;
    US  I1237 :1;
    US  I1238 :1;
    US  I1239 :1;
    US  I1240 :5;
} RmaTcCoreSimpleNoList;
typedef struct {
    RP  I1230;
    RP  I660;
    U  I1231;
    scalar  I1132;
    scalar  I1232;
    US  I1233 :1;
    US  I1234 :1;
    US  I1235 :1;
    US  I1236 :1;
    US  I1237 :1;
    US  I1238 :1;
    US  I1239 :1;
    US  I1240 :5;
    RP  I1241;
} RmaTcCoreConditionalNoList;
typedef struct {
    RP  I1230;
    RP  I660;
    U  I1231;
    scalar  I1132;
    scalar  I1232;
    US  I1233 :1;
    US  I1234 :1;
    US  I1235 :1;
    US  I1236 :1;
    US  I1237 :1;
    US  I1238 :1;
    US  I1239 :1;
    US  I1240 :5;
    RP  I1241;
    RP  I1242;
} RmaTcCoreConditionalOptNoList;
typedef struct {
    RP  I1230;
    RP  I660;
    U  I1231;
    scalar  I1132;
    scalar  I1232;
    US  I1233 :1;
    US  I1234 :1;
    US  I1235 :1;
    US  I1236 :1;
    US  I1237 :1;
    US  I1238 :1;
    US  I1239 :1;
    US  I1240 :5;
    RP  I1242;
    RP  I1243;
    U  I1244;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoList;
typedef struct {
    RP  I1230;
    RP  I660;
    U  I1231;
    scalar  I1132;
    scalar  I1232;
    US  I1233 :1;
    US  I1234 :1;
    US  I1235 :1;
    US  I1236 :1;
    US  I1237 :1;
    US  I1238 :1;
    US  I1239 :1;
    US  I1240 :5;
    RP  I1242;
    RP  I1243;
    RP  I1139;
    U  I1244;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoListMdb;
typedef struct {
    RP  I1230;
    RP  I660;
    U  I1231;
    scalar  I1132;
    scalar  I1232;
    US  I1233 :1;
    US  I1234 :1;
    US  I1235 :1;
    US  I1236 :1;
    US  I1237 :1;
    US  I1238 :1;
    US  I1239 :1;
    US  I1240 :5;
    RP  I1241;
    RP  I1139;
} RmaTcCoreConditionalNoListMdb;
typedef struct {
    RP  I1230;
    RP  I660;
    U  I1231;
    scalar  I1132;
    scalar  I1232;
    US  I1233 :1;
    US  I1234 :1;
    US  I1235 :1;
    US  I1236 :1;
    US  I1237 :1;
    US  I1238 :1;
    US  I1239 :1;
    US  I1240 :5;
    U  I1246;
    RP  I1247;
    RP  I1248;
    RP  I1241;
    RP  I1249;
    RP  I1250;
    RmaTimeStamp  I1251;
} RmaTcCoreNochange;
typedef struct {
    RP  I1252;
    RP  I969;
} RmaTcCoreNochangeList;
typedef struct {
    RP  I1230;
    RP  I660;
    U  I1231;
    scalar  I1132;
    scalar  I1232;
    US  I1233 :1;
    US  I1234 :1;
    US  I1235 :1;
    US  I1236 :1;
    US  I1237 :1;
    US  I1238 :1;
    US  I1239 :1;
    US  I1240 :5;
    RP  I1241;
    RmaEblk  I665;
    U  I1253;
} RmaTcCoreFullskew;
typedef struct {
    RP  I1254;
    RP  I969;
} RmaTcCoreFullskewList;
typedef struct {
    RP  I1225;
    RmaTimeStamp  I1255;
    scalar  I1256;
} RmaConditionalTSLoadNoList;
typedef struct {
    RP  I969;
    RP  I1225;
    RmaTimeStamp  I1255;
    scalar  I1256;
} RmaConditionalTSLoad;
typedef struct {
    RmaTimeStamp  I1255;
    scalar  I1256;
    US  I1132;
    RP  I1242;
} RmaConditionalTSLoadOptNoList;
typedef struct {
    RP  I969;
    RmaTimeStamp  I1255;
    scalar  I1256;
    US  I1132;
    RP  I1242;
} RmaConditionalTSLoadOpt;
typedef struct {
    RP  I1242;
    RP  I1257;
    U  I1244;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoList;
typedef struct {
    RP  I1139;
    RP  I1242;
    RP  I1257;
    U  I1244;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoListMdb;
typedef struct {
    RP  I969;
    RP  I1242;
    RP  I1257;
    U  I1244;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtc;
typedef struct {
    U  I1258;
    U  I1259;
    FlatNodeNum  I1087;
    U  I977;
    U  I1260;
    U  I1261;
    RmaIbfPcode  I1128;
    union {
        scalar  I1262;
        vec32  I1263;
        scalar  * I1264;
        vec32  * I1265;
    } val;
} RmaScanSwitchData;
typedef struct {
    U  I1258;
    U  I1259;
    U  I977;
    U  I1266;
    FlatNodeNum  I1087;
    RmaIbfPcode  I1128;
    union {
        scalar  I1262;
        vec32  I1263;
        scalar  * I1264;
        vec32  * I1265;
        double I1267;
        scalar  * I1268;
    } val;
} RmaRtvsGateData;
typedef struct {
    RP  I969;
    RP  I745;
    RP  I1269;
} RmaDoublyLinkedListElem;
typedef struct {
    RP  I1270;
    RP  I1271;
    U  I1272 :1;
    U  finterpreted :1;
    U  I1274 :1;
    U  I1275 :4;
    U  I1276 :1;
    U  I1069 :1;
    U  I1277 :1;
    U  I1278;
} RmaSwitchGateInCbkListInfo;
typedef struct {
    union {
        RmaDoublyLinkedListElem  I1800;
        RmaSwitchGateInCbkListInfo  I2;
    } I641;
    RmaIbfPcode  I1128;
} RmaSwitchGate;
typedef struct RmaNonEdgeLoadData1_ {
    US  I1279;
    scalar  val;
    scalar  I1280 :1;
    scalar  I1281 :1;
    scalar  I1282 :3;
    scalar  I1283 :1;
    scalar  I1284 :1;
    scalar  I1285 :1;
    U  I1286;
    U  I1287;
    RP  I758;
    RP  I1288;
    RP  I1087;
    RP  I1289;
    RP  I1290;
} RmaNonEdgeLoadData1;
typedef struct RmaNonEdgeLoadHdr1_ {
    UB  I1280;
    UB  I1291;
    UB  I1045;
    RmaNonEdgeLoadData1  * I1169;
    RmaNonEdgeLoadData1  * I745;
    RP  I1188;
    void * I1170;
} RmaNonEdgeLoadHdr1;
typedef struct RmaNonEdgeLoadHdrPrl1_ {
    U  I1292;
    RP  I660;
} RmaNonEdgeLoadHdrPrl1;
typedef struct RmaNonEdgeLoadArrayHdr1_ {
    UB  I1280 :1;
    UB  I1291 :1;
    UB  I1045;
    int I629;
    RmaNonEdgeLoadData1  * I633;
    U  * I1293;
    RP  I1188;
    void * I1170;
} RmaNonEdgeLoadArrayHdr1;
typedef struct RmaNonEdgeLoadDataArray1_ {
    U  I1294;
} RmaNonEdgeLoadDataArray1;
typedef struct RmaChildClockProp_ {
    RP  I758;
    RP  I1295;
    RP  I1087;
    RP  pcode;
    scalar  val;
} RmaChildClockProp;
typedef struct RmaChildClockPropList1_ {
    RmaChildClockProp  * I1169;
    RmaChildClockProp  * I745;
} RmaChildClockPropList1;
typedef struct {
    UB  I1296;
    UB  I1297 :1;
    UB  I1298 :1;
    UB  I1299 :1;
    UB  I1300 :1;
    UB  I836 :4;
    US  cedges;
    RP  I1301;
} RmaMasterXpropLoadHdr;
typedef struct {
    UB  I1296;
    UB  I1302;
    UB  I1303;
    UB  I1304 :1;
    UB  I1305 :1;
    UB  I836 :6;
    U  cedges;
} RmaXpropLoadHdr;
typedef struct {
    UB  I1302;
    UB  I1303;
    UB  I1306;
    UB  I1307;
    U  cedges :29;
    U  I1298 :1;
    U  I1308 :1;
    U  I1309 :1;
    U  I1310;
    U  I1311;
    RP  I1312;
    RP  I1313;
    RmaRtlEdgeBlockHdr  * I1314;
} RmaChildXpropLoadHdr;
struct clock_load {
    U  I234 :5;
    U  I235 :12;
    U  I236 :1;
    U  I237 :2;
    U  I238 :1;
    U  I239 :1;
    U  I240 :1;
    U  I241 :9;
    U  I242;
    U  I243;
    void (* pfn)(void * I245, char val);
};
typedef struct clock_data {
    U  I250 :1;
    U  I251 :1;
    U  I252 :1;
    U  I253 :1;
    U  I234 :5;
    U  I235 :12;
    U  I254 :6;
    U  I255 :1;
    U  I237 :2;
    U  I238 :1;
    U  I241 :1;
    U  I256;
    U  I257;
    U  I258;
    U  I242;
    U  I259;
    U  I260;
    U  I261;
    U  I262;
    U  I263;
} HdbsClockData;
struct clock_hiconn {
    U  I267;
    U  I268;
    U  I242;
    U  I237;
};
typedef union _RmaCbkMemOptUnion {
    RP  I1315;
    RP  I1316;
    RP  I1317;
} RmaCbkMemOptUnion;
typedef struct _RmaDaiOptCg {
    RmaCbkMemOptUnion  I1318;
} RmaDaiOptCg;
struct futq_slot2 {
    U  I705;
    U   I706[32];
};
struct futq_slot1 {
    U  I702;
    struct futq_slot2  I703[32];
};
struct futq_info {
    scalar  * I697;
    U  I698;
    U  I699;
    struct futq_slot1  I700[32];
};
struct futq {
    struct futq * I686;
    struct futq * I688;
    RmaEblk  * I689;
    RmaEblk  * I690;
    U  I670;
    U  I1;
    DEblkPoolT  * I691;
};
struct sched_table {
    struct futq * I692;
    struct futq I693;
    struct hash_bucket * I694;
    struct hash_bucket * I696;
};
struct dummyq_struct {
    clock_struct  I1319;
    EBLK  * I1320;
    EBLK  * I1321;
    EBLK  * I1322;
    struct futq * I1323;
    struct futq * I1324;
    struct futq * I1325;
    struct sched_table * I1326;
    struct futq_info * I1328;
    struct futq_info * I1330;
    U  I1331;
    U  I1332;
    U  I1333;
    U  I1334;
    U  I1335;
    U  I1336;
    U  I1337;
    struct millenium * I1338;
    EBLK  * I1340;
    EBLK  * I1341;
    EBLK  * I1342;
    EBLK  * I1343;
    EBLK  * I1344;
    EBLK  * I1345;
    EBLK  * I1346;
    EBLK  * I1347;
    EBLK  * I1348;
    EBLK  * I1349;
    EBLK  * I1350;
    EBLK  * I1351;
    EBLK  * I1352;
    EBLK  * I1353;
    EBLK  * I1354;
    EBLK  * I1355;
    EBLK  * I1356;
    MPS  * I1357;
    struct retain_t * I1358;
    EBLK  * I1359;
    EBLK  * I1360;
    EBLK  * I1361;
    EBLK  * I1362;
    EBLK  * I1363;
    EBLK  * I1364;
    EBLK  * I1365;
    EBLK  * I1366;
    EBLK  * I1367;
    EBLK  * I1368;
    EBLK  * I1369;
    EBLK  * I1370;
    EBLK  * I1371;
    EBLK  * I1372;
    EBLK  * I1373;
    EBLK  * I1374;
    EBLK  * I1375;
    EBLK  * I1376;
    EBLK  * I1377;
    EBLK  * I1378;
    EBLK  * I1379;
    EBLK  * I1380;
    EBLK  * I1381;
    EBLK  * I1382;
    EBLK  * I1383;
    EBLK  * I1384;
    EBLK  I1385;
    EBLK  * I1386;
    EBLK  * I1387;
    int I1388;
    struct vcs_globals_t * I1389;
    clock_struct  I1391;
    unsigned long long I1392;
    EBLK  * I1393;
    EBLK  * I1394;
    void * I1395;
    U  semilerOptQueuesFlag;
    U  I1397;
};
typedef void (* FP)(void *  , scalar   );
typedef void (* FP1)(void *  );
typedef void (* FPRAP)(void *  , vec32  *  , U   );
typedef U  (* FPU1)(void *  );
typedef void (* FPV)(void *  , UB  *  );
typedef void (* FPVU)(void *  , UB  *  , U   );
typedef void (* FPDP)(void *  , void *  , scalar   );
typedef void (* FPVDP)(void *  , void *  , void *  );
typedef void (* FPLSEL)(void *  , scalar   , U   );
typedef void (* FPLSELV)(void *  , vec32  *  , U   , U   );
typedef void (* FPFPV)(UB  *  , UB  *  , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPFA)(UB  *  , UB  *  , U   , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPRPV)(UB  *  , U   , U   , U   );
typedef void (* FPEVCDLSEL)(void *  , scalar   , U   , UB  *  );
typedef void (* FPEVCDLSELV)(void *  , vec32  *  , U   , U   , UB  *  );
typedef void (* FPNTYPE_L)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_H)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_LPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_HPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef struct _lqueue {
    int I1398;
    struct _lqueue * I716;
    EBLK  * I1400;
    EBLK  * I669;
    DEblkPoolT  * I691;
} Queue;
typedef struct {
    void * I1401;
    void * I1402;
    void * I1403;
    void * I1404;
    void * I1405[2];
    void * I1406;
} ClkLevel;
typedef struct {
    unsigned long long I1407;
    EBLK  I1308;
    U  I1408;
    U  I1409;
    union {
        void * pHeap;
        Queue  * pList;
    } I641;
    unsigned long long I1410;
    ClkLevel  I1411;
    Queue   I1412[1];
} Qhdr;
extern UB   Xvalchg[];
extern UB   X4val[];
extern UB   X3val[];
extern UB   X2val[];
extern UB   XcvtstrTR[];
extern UB   Xcvtstr[];
extern UB   Xbuf[];
extern UB   Xbitnot[];
extern UB   Xwor[];
extern UB   Xwand[];
extern U   Xbitnot4val[];
extern UB   globalTable1Input[];
extern __thread unsigned long long vcs_clocks;
extern __thread unsigned long long ref_vcs_clocks;
extern UB   Xunion[];
extern UB   vcsXunionCg[];
extern UB   vcsXworCg[];
extern UB   vcsXwandCg[];
extern U  fRTFrcRelCbk;
extern FP  txpFnPtr;
extern UP   bepatsFunctionArray[];
extern FP   rmaFunctionArray[];
extern UP   rmaFunctionRtlArray[];
extern UP   rmaFunctionHsRtlArray[];
extern FP   rmaFunctionLRArray[];
extern U  rmaFunctionCount;
extern U  rmaFunctionLRCount;
extern U  rmaFunctionLRDummyCount;
extern UP  rmaFunctionDummyEndPtr;
extern FP   rmaFunctionFanoutArray[];
extern __thread UB  dummyScalar;
extern __thread UB  fScalarIsForced;
extern __thread UB  fScalarIsReleased;
extern __thread UB  fScalarIsDeposited;
extern U  fNotimingchecks;
extern U  fFsdbDumpOn;
extern RP  * iparr;
extern FP1  * rmaPostAnySchedFnPtr;
extern FP1  * rmaPostAnySchedFnSamplePtr;
extern FP1  * rmaPostAnySchedVFnPtr;
extern FP1  * rmaPostAnySchedWFnPtr;
extern FP1  * rmaPostAnySchedEFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusNonCongruentFnPtr;
extern FP1  * rmaPostSchedUpdateEvTrigFnPtr;
extern FP1  * rmaSched0UpdateEvTrigFnPtr;
extern FP1  * rmaPostSchedRecoveryResetDbsFnPtr;
extern U  fGblDataOrTime0Prop;
extern UB   rmaEdgeStatusValArr[];
extern UB   rmaposEdgeStatusArray[];
extern UB   rmanegEdgeStatusArray[];
extern FP1  * propForceCbkSPostSchedCgFnPtr;
extern FP1  * propForceSPostSchedCgFnPtr;
extern FP1  * propForceSPostSchedNativeVcCgFnPtr;
extern U  VCS_NCBK_Enabled;
extern UB  * ptableGbl;
extern U  * vcs_ptableOffsetsGbl;
extern UB  * expandedClkValues;
extern __thread Qhdr  * lvlQueue;
extern __thread unsigned threadIndex;
extern __thread unsigned fBufferingEvent;
extern int cPeblkThreads;
extern US   xedges[];
extern U  mhdl_delta_count;
extern U  ignoreSchedForScanOpt;
extern U  fignoreSchedForDeadComboCloud;
extern int fZeroUser;
extern U  fEveBusPullVal;
extern U  fEveBusPullFlag;
extern U  fFutEventPRL;
extern U  fParallelEBLK;
extern __thread UB  fNettypeIsForced;
extern __thread UB  fNettypeIsReleased;
extern EBLK  * peblkFutQ1Head;
extern EBLK  * peblkFutQ1Tail;
extern US  * edgeActionT;
extern unsigned long long * derivedClk;
extern U  fHashTableSize;
extern U  fSkipStrChangeOnDelay;
extern U  fHsimRuntimeSdfOpt;
extern U  fSkipMpTsUpdateOnStr;
extern scalar   edgeChangeLookUp[4][4];
extern U  fDoingTime0Prop;
extern U  fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U  fLoopReportRT;
extern U  fIsCalledFromWaveform;
extern U  rmaProfEvtProp;
extern U  semilerOptQueuesFlag;
extern int semilerOpt;


extern void *mempcpy(void* s1, void* s2, unsigned n);
extern RP* rmaGetDynamicVcdLocation(U archiveId, U patIdx, UB* pupdate);
extern UB* rmaEvalDelays(UB* pcode, scalar val, void* pwaveform, U* wf_cloads);
extern UB* rmaEvalDelaysV(UB* pcode, vec32* pval);
extern void rmaPopTransEvent(UB* pcode);
extern void rmaSetupFuncArray(UP* ra, U c, U w);
extern void rmaSetupRTLoopReportPtrs(UP* funcs, UP* rtlFuncs, U cnt, U cntDummy, UP end);
extern void SinitHsimPats(void);
extern void VVrpDaicb(void* ip, U nIndex);
extern int SDaicb(void *ip, U nIndex);
extern void SDaicbForHsimNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimNoFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimWithFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimNoFlagDynElabFrcRel(U* mem, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimNoFlagFrcRel(void* pDaiCb, unsigned char reason, int msb, int lsb, int ndx);
extern void hsimDispatchForVcd(RP p, U val);
extern void* hsimGetCbkMemOptCallback(RP p);
extern void hsimDispatchNoDynElabS(RP* p, U val, U isStrength);
extern void hsimDispatchDANoDynElabS(RP* p, U val, UB* da_byte, U isStrength);
extern U slaveTogglesThisTime;
extern void* hsimGetCbkPtrNoDynElab(RP p);
extern void hsimDispatchDynElabS(U** pvcdarr, U** pcbkarr, U val, U isScalForced, U isScalReleased, U isStrength);
extern void hsimDispatchNoDynElabVector(RP* /*RmaDaiOptCg* */p, void* pval, U /*RmaValueType*/ vt, U cbits);
extern void copyAndPropRootCbkCgS(RmaRootCbkCg* pRootCbk, scalar val);
extern void copyAndPropRootCbkCgV(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgW(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgE(RmaRootCbkCg* rootCbk, scalar* pval);
extern void Wsvvar_callback_non_dynamic1(RP* ptr, int);
extern void rmaExecEvSyncList(RP plist);
extern void Wsvvar_callback_virt_intf(RP* ptr);
extern void Wsvvar_callback_hsim_var(RP* ptr);
extern void checkAndConvertVec32To2State(vec32* value, vec32* svalue, U cbits, U* pforcedBits);
extern unsigned int fGblDataOrTime0Prop;
extern void SchedSemiLerMP1(UB* pmps, U partId);
extern void SchedSemiLerMPO(UB* pmpso, U partId);
extern void rmaDummyPropagate(void);
extern RP rmaTestCg(RP pcode, U vt, UB* value);
extern void hsUpdateModpathTimeStamp(UB* pmps);
extern void doMpd32One(UB* pmps);
extern void doMpdCommon(MPS* pmps);
extern TimeStamp GET_DIFF_DELAY_FUNC(TimeStamp ts);
extern void SchedSemiLerMP(UB* ppulse, U partId);
extern EBLK *peblkFutQ1Head;
extern EBLK *peblkFutQ1Tail;
extern void scheduleuna(UB *e, U t);
extern void scheduleuna_mp(EBLK *e, unsigned t);
extern void schedule(UB *e, U t);
extern void sched_hsopt(struct dummyq_struct * pQ, EBLK *e, U t);
extern void sched_millenium(struct dummyq_struct * pQ, void *e, U thigh, U t);
extern void schedule_1(EBLK *e);
extern void sched0(UB *e);
extern void sched0lq(EBLK *e);
extern void sched0lqnc(EBLK *e);
extern void sched0una(UB *e);
extern void sched0una_th(struct dummyq_struct *pq, UB *e);
extern void hsopt_sched0u_th(struct dummyq_struct *pq, UB *e);
extern void scheduleuna_mp_th(struct dummyq_struct *pq, EBLK *e, unsigned t);
extern void schedal(UB *e);
extern void sched0_th(struct dummyq_struct * pQ, EBLK *e);
extern void sched0u(UB *e);
extern void sched0u_th(struct dummyq_struct *pq, UB *e);
extern void sched0_hsim_front_th(struct dummyq_struct * pQ, UB *e);
extern void sched0_hsim_frontlq_th(struct dummyq_struct * pQ, UB *e);
extern void sched0lq_th(struct dummyq_struct * pQ, UB *e);
extern void schedal_th(struct dummyq_struct * pQ, UB *e);
extern void scheduleuna_th(struct dummyq_struct * pQ, void *e, U t);
extern void sched64cuna_th(struct dummyq_struct * pQ, void *e, U h, U l);
extern void schedule_th(struct dummyq_struct * pQ, UB *e, U t);
extern void schedule_front_th(struct dummyq_struct * pQ, UB *e, U t);
extern void schedule_1_th(struct dummyq_struct * pQ, EBLK *peblk);
extern void schedule_1_front_th(struct dummyq_struct * pQ, EBLK *peblk);
extern void SetupLER_th(struct dummyq_struct * pQ, EBLK *e);
extern void FsdbReportClkGlitch(UB*,U);
extern void AddToClkGLitchArray(EBLK*);
extern void SchedSemiLer_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXP_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXPFreeVar_th(struct dummyq_struct * pQ, EBLK *e);
extern U getVcdFlags(UB *ip);
extern void VVrpNonEventNonRegdScalarForHsimOpt(void* ip, U nIndex);
extern void VVrpNonEventNonRegdScalarForHsimOpt2(void* ip, U nIndex);
extern void SchedSemiLerTBReactiveRegion(struct eblk* peblk);
extern void SchedSemiLerTBReactiveRegion_th(struct eblk* peblk, U partId);
extern void SchedSemiLerTr(UB* peblk, U partId);
extern void SchedSemiLerNBA(UB* peblk, U partId);
extern void NBA_Semiler(void *ip, void *pNBS);
extern void sched0sd_hsim(UB* peblk);
extern void vcs_sched0sd_hsim_udpclk(UB* peblk);
extern void vcs_sched0sd_hsim_udpclkopt(UB* peblk);
extern void sched0sd_hsim_PRL(UB* peblk);
extern void sched0lq_parallel_clk(EBLK* peblk);
extern void sched0lq_de(U* pe, void* ip, void* prout);
extern void sched0lq_hsopt_nonfgp_de(U* pe, void* ip, void* prout);
extern void sched0lq_hsopt_parallel_de(U* pe, void* ip, void* prout);
extern void sched0_de_inl(void* ip, void* prout);
extern void rmaPostDynamicSchedDeltaGate(UB* pcode);
extern U    isRtlClockScheduled(EBLK* peblk);
extern void doFgpRaceCheck(UB* pcode, UB* p, U flag);
extern void doSanityLvlCheck();
extern void sched0lq_dbsed_ova_jaguar(EBLK* peblk);
extern void sched0lq_nondbsed_ova_jaguar(EBLK* peblk);
extern void sched0lq_parallel_ova(EBLK* peblk);
extern void sched0lq_parallel_ova_precheck(EBLK* peblk);
extern void rmaDlpEvalSeqPrim(UB* peblk, UB val, UB preval);
extern void appendNtcEvent(UB* phdr, scalar s, U schedDelta);
extern void appendTransEventS(RmaTransEventHdr* phdr, scalar s, U schedDelta);
extern void schedRetainHsim(MPS* pMPS, scalar sv, scalar pv);
extern void updateRetainHsim(MPS* pMPS,scalar sv, scalar pv);
extern void hsimCountXEdges(void* record,  scalar s);
extern void hsimRegisterEdge(void* sm,  scalar s);
extern EBLK* pvcsGetLastEventEblk(U thid);
extern void insertTransEventIC(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, int re, UB* predd, U fpdd);
extern void insertNtcEventRF(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, U* delays);
extern U doTimingViolation(RmaTimeStamp ts,RP* pdata, U fskew, U limit, U floaded, U fcondopt, RmaTimeStamp tsNochange);
extern void sched_gate_hsim(EBLK* peblk, unsigned t, RP* offset, U gd_info, U encodeInPcode, void* propValue);
extern void sched_gate_hsim_front(EBLK* peblk, unsigned t, RP* offset, U gd_info, U encodeInPcode, void* propValue);
extern int getCurSchedRegion();
extern FP getRoutPtr(RP, U);
extern U rmaChangeCheckAndUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern void rmaUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaChangeCheckAndUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaLhsPartSelUpdateE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaUpdateWithForceSelectorE(scalar* pvalDst, scalar* pvalSrc, U cbits, U* pforceSelector);
extern void rmaUpdateWFromE(vec32* pvalDst, scalar* pvalSrc, U cbits);
extern void rmaUpdateWUFromE(U* pv, scalar* pval, U cbits);
extern U rmaLhsPartSelWithChangeCheckE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaLhsPartSelWFromE(vec32* pvalDst, scalar* pvalSrc, U index,U width);
extern U rmaChangeCheckAndUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern void *VCSCalloc(size_t size, size_t count);
extern void *VCSMalloc(size_t size);
extern void VCSFree(void *ptr);
extern U rmaLhsPartSelWithChangeCheckW(vec32* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern U rmaLhsPartSelWithChangeCheckEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelUpdateW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void rmaEvalWunionW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWorW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWandW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalUnionE(scalar* dst, scalar* src, U cbits, U count, RP ptable);
typedef U RmaCgFunctionType;
extern RmaIbfPcode* rmaEvalPartSelectsW(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce, UB* pevcdStatus);
extern RmaIbfPcode* rmaEvalPartSelectsWLe32(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce, UB* pevcdStatus);
extern RmaIbfPcode* rmaEvalPartSelectsWToE(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsEToE(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce, UB* pevcdStatus);
extern RmaIbfPcode* rmaEvalPartSelectsEToW(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern U rmaEvalBitPosEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U VcsForceVecVCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U/*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecVCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecWCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecWCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecECg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecACg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecCg(UB* pcode, UB* pvDst, U ibeginDst, U width, U /*RmaValueType*/ type,U fisRoot, UB* prhsDst, U frhs, U* pforcedbits);
extern U VcsDriveBitsAndDoChangeCheckV(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckW(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckE(scalar* pvSel, scalar* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern void cgvecDebug_Eblk(UB* pcode);
extern U rmaCmpW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void copyVec32ArrMask(vec32* pv1, vec32* pv2, U len, U* mask);
extern void* memcpy(void*, const void*, size_t);
extern int memcmp(const void*, const void*, size_t);
extern void propagateScanOptPathVal(EBLK *peblk);
extern UB* rmaProcessRtvsSwitches(UB* pcode, scalar val);
extern UB* rmaProcessScanSwitches(UB* pcode, scalar val);
extern UB* rmaProcessScanSwitchesV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanoptDump(UB* pcode, scalar val);
extern UB* rmaProcessScanoptDumpV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanChainOptSeqPrims(UB* pcode, scalar val);
extern void schedResetRecoveryDbs(U cedges, EBLK* peblkFirst);
extern UB* rmaEvalUnaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVOneFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVLargeFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalAndOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpV(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpV(UB* pcode, vec32* value);
extern UB* rmaEvalTernaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalTernaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalBinaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpS(UB* pcode, scalar val);
extern scalar rmaGetScalarFromWCg(vec32* pval, U index);
extern void rmaSetScalarInWCg(vec32* pval, U index, scalar s);
extern void rmaSetWInW(vec32* dst, vec32* src, U index, U indexSrc, U width);
extern void setHsimFunc(void* ip, U offset);
extern void vcs_updateHsimFunc(void* ip, U offset);
extern void unsetHsimFunc(void* ip);
extern U fProfEvtProp;
extern UB* getEvcdStatusByFlagsE(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsV(vec32* pvec32, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsW(vec32* pvec32, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsS(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table);
extern UB* getSingleDrvEvcdStatusS(UB value, U fTBDriver);
extern UB* getSingleDrvEvcdStatusE(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getSingleDrvEvcdStatusV(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getSingleDrvEvcdStatusW(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getEvcdStatusByDrvEvcdStatus(UB* pdrvevcdStatus, U cdrivers, UB* table, U cbits);
extern void evcdCallback(UP pcode, U cbits);
extern UB* getSavedEvcdStatus(void);
extern void saveEvcdStatus(UB*);
extern void mhdlMarkExport(void*, U);
extern void levelInsertQueue(int);
extern void levelInsertQueueGL(int);
extern void VcsRciRtl(RP pcode);
extern void VcsRciSCompiledLoad(scalar* pcode, scalar ibnVal);
extern U fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U fLoopReportRT;
extern void rtSched0LoopDectDumpProcess(void* e, void* rtn, void* PQ);
extern void pushHsimRtnCtxt(void* pcode);
extern void popHsimRtnCtxt();
extern EBLK* loopReportInlinedSched0Wrapper(EBLK *peblk);
extern void loopReportSched0Wrapper(EBLK *peblk, unsigned int sfType, unsigned int fTH, struct dummyq_struct* pq);
extern void loopReportSchedSemiLerWrapper(EBLK *peblk, int sfType);
extern void CallGraphPushNodeAndAddToGraph(UP flatNode, UP instNum, U dummy);
extern void CallGraphPopNode(void);
extern RP elabGetIpTpl(U in);
extern U rmaEvalBitBothEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQXW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval01EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval0XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval10EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval1XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX1EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX0EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitPosEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitBothEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern void rmaScheduleNbaGate(RP pcode, scalar val);
extern void rmaEvalRtlEdgeLoads(RmaRtlEdgeBlockHdr *phdr, US clkEdge, scalar clkVal, scalar prevClkVal, scalar val4,   scalar prevval4, scalar master4val);
extern void rmaEvaluateDynamicGateLoadsCg(RP p, scalar s);
extern void rmaEvaluateFusedWithDynamicGateLoadsCg(RP p, scalar s);
extern void rmaScheduleGatedClockEdgeLoadNew(UB* p, US* ea, U flags, UB* plist, UB* pprevlist, scalar v, scalar pv);
extern void rmaScheduleGatedClockEdgeLoad(UB* p, US* ea, U flags, UB* plist, UB* pprevlist, scalar v);
extern void vcsCheckIfClkValValid(U val, U index);
extern void rmaRemoveNonEdgeLoads(UB* pcode);
extern void rmaRecordEvents(HsimNodeRecord *pnr);
extern void handlePCBs(UB* p, U i);
extern void markMasterClkOvaLists(U fdbs, RP p);
extern void rmaChildClockPropAfterWrite(UB* p);
extern void rmaSchedChildClockPropAfterWrite(UB* p, UB* pmasterList, UB val);
extern void rmaChangeListForMovedGates(UB clkVal, UB f10Edge, UB* subMasterVal, UB* plist, RP* p, U count);
extern void rmaEvalSeqPrimLoadsByteArray(UB* pcode, UB val, UB prevval4);
extern void rmaEvalSeqPrimLoadsByteArrayX(UB* pcode, UB val, UB prevval4);
extern void vcsRmaEvalSeqPrimLoadsByteArraySCT(UB* pcode, UB val, UB prevval4, U c);
extern void rmaEvalSimonCellLoadsByteArray(UB* pcode, UB val, UB prevval4);
extern void rmaEvalSimonCellLoadsByteArrayX(UB* pcode, UB val, UB prevval4);
extern void vcsAbortForBadEBlk(void);
extern scalar edgeChangeLookUp[4][4];
extern void Wsvvar_sched_virt_intf_eval(RP* ptr, char val);
extern void vcs_hwcosim_drive_dut_scalar(U id, char val);
extern void vcs_hwcosim_drive_dut_vector_4state(U id, vec32* val);
extern U vcs_rmaGetClkValForSeqUdpLayoutOnClkOpt(UB* poutput);
extern U vcs_rmaGetClkValForSeqUdpLayoutOnClk(UB* poutput);
extern U vcs_rmaGetClkValForSeqUdp(UB* poutput);
extern void vcs_rmaGetWFForSeqUdp(UB* phead);
extern U add_new_event(void* wfclock, unsigned char s);
extern U has_periodicity_started(void *wfclock);
extern void fire_scalarclock_start_cbk(void* wfclock, void* pdata);
extern void fire_scalarclock_end_cbk(void* wfclock);
extern void patchWfTs(RP _ppwf);
extern void patchWfWp(RP _ppwf);
extern void patchWfS(RP _ppwf);
extern void patchWfH(RP _ppwf);
extern U is_connected(void* wfclock, U idx);
extern U is_delay_connected(void* wfclock, U idx, scalar *out_prev_val);
extern void set_auto_sched_for_dbs_loads(void* wfclock, scalar edge);
extern U Fsim_handle_wreal_faults(void);
extern U is_event_record_needed(void *waveform);
extern U rmaIsS2State(scalar s);
extern U rmaIsV2State(vec32* pval, U cbits);
extern U rmaIsW2State(vec32* pval, U cbits);
extern U rmaIsE2State(scalar* pval, U cbits);
extern void rmaUpdateRecordFor2State(HsimNodeRecord* record, U f2state);
typedef void (*FuncPtr)();
static inline U asm_bsf (U in)
{
#if defined(linux)
    U out;
#if !defined(__aarch64__)
    asm ("movl %1, %%eax; bsf %%eax, %%eax; movl %%eax, %0;"
        :"=r"(out)
        :"r"(in)
        :"%eax"
        );
#else
    out = ffs(in) - 1;
#endif
    return out;
#else
    return 0;
#endif
}


#ifdef __cplusplus
extern "C" {
#endif
void  rmaPropagate0_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate0_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate0_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate0_r_simv_daidir (UB  * pcode);
void  rmaPropagate0_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate1_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate1_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate1_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate1_r_simv_daidir (UB  * pcode);
void  rmaPropagate1_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate2_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate2_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate2_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate2_r_simv_daidir (UB  * pcode);
void  rmaPropagate2_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate3_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate3_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate3_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate3_r_simv_daidir (UB  * pcode);
void  rmaPropagate3_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate4_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate4_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate4_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate4_r_simv_daidir (UB  * pcode);
void  rmaPropagate4_t0_simv_daidir (UB  * pcode, UB  val);
void  rmaPropagate4_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate5_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate5_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate5_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate5_r_simv_daidir (UB  * pcode);
void  rmaPropagate5_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate6_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate6_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate6_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate6_r_simv_daidir (UB  * pcode);
void  rmaPropagate6_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate7_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate7_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate7_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate7_r_simv_daidir (UB  * pcode);
void  rmaPropagate7_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate8_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate8_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate8_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate8_r_simv_daidir (UB  * pcode);
void  rmaPropagate8_t0_simv_daidir (UB  * pcode, UB  val);
void  rmaPropagate8_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate18_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate18_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate18_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate18_r_simv_daidir (UB  * pcode);
void  rmaPropagate18_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate20_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate20_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate20_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate26_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate28_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate28_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate28_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate28_r_simv_daidir (UB  * pcode);
void  rmaPropagate28_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate29_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate29_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate29_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate29_r_simv_daidir (UB  * pcode);
void  rmaPropagate29_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate30_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate30_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate30_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate30_r_simv_daidir (UB  * pcode);
void  rmaPropagate30_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate31_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate31_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate31_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate31_r_simv_daidir (UB  * pcode);
void  rmaPropagate31_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate33_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate33_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate33_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate33_r_simv_daidir (UB  * pcode);
void  rmaPropagate33_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate34_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate34_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate34_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate34_r_simv_daidir (UB  * pcode);
void  rmaPropagate34_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate35_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate35_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate35_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate35_r_simv_daidir (UB  * pcode);
void  rmaPropagate35_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate38_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate38_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate38_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate38_r_simv_daidir (UB  * pcode);
void  rmaPropagate38_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate39_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate39_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate39_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate39_r_simv_daidir (UB  * pcode);
void  rmaPropagate39_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate40_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate40_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate40_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate40_r_simv_daidir (UB  * pcode);
void  rmaPropagate40_t0_simv_daidir (UB  * pcode, UB  val);
void  rmaPropagate40_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate42_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate42_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate42_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate42_r_simv_daidir (UB  * pcode);
void  rmaPropagate42_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate43_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate43_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate43_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate43_r_simv_daidir (UB  * pcode);
void  rmaPropagate43_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate44_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate44_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate44_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate44_r_simv_daidir (UB  * pcode);
void  rmaPropagate44_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate45_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate46_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate46_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate46_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate46_r_simv_daidir (UB  * pcode);
void  rmaPropagate46_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate53_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate53_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate53_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate60_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate60_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate60_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate60_r_simv_daidir (UB  * pcode);
void  rmaPropagate60_t0_simv_daidir (UB  * pcode, UB  val);
void  rmaPropagate60_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate61_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate61_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate61_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate61_r_simv_daidir (UB  * pcode);
void  rmaPropagate61_t0_simv_daidir (UB  * pcode, UB  val);
void  rmaPropagate61_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate62_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate62_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate62_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate62_r_simv_daidir (UB  * pcode);
void  rmaPropagate62_t0_simv_daidir (UB  * pcode, UB  val);
void  rmaPropagate62_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate63_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate63_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate63_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate63_r_simv_daidir (UB  * pcode);
void  rmaPropagate63_t0_simv_daidir (UB  * pcode, UB  val);
void  rmaPropagate63_wn_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate64_p_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate64_simv_daidir (UB  * pcode, scalar  val);
void  rmaPropagate64_f_simv_daidir (UB  * pcode, scalar  val, U  I619, scalar  * I1442, U  did);
void  rmaPropagate64_r_simv_daidir (UB  * pcode);
void  rmaPropagate64_t0_simv_daidir (UB  * pcode, UB  val);
void  rmaPropagate64_wn_simv_daidir (UB  * pcode, scalar  val);
void  schedNewEvent (struct dummyq_struct * I1424, EBLK  * I1419, U  I626);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
  }
#endif
#endif /*__DO_RMAHDR_*/

